CREATE TABLE `tbl_students` (
 `id` INT(11) NOT NULL AUTO_INCREMENT,
 `fullname` VARCHAR(100) DEFAULT NULL,
 `email` VARCHAR(50) DEFAULT NULL,
 `password` VARCHAR(15) DEFAULT NULL,
 PRIMARY KEY (`id`)
);

